[feat] : 채팅방 메시지 조회, 채팅방 메시지 읽음 처리
Programmers-HandsUp/BE-handsup pull request #102
Opened 2024-03-15 13:40 UTC by hyun2371

### 📑 작업 상세 내용

- 채팅방 메시지 조회
 - repository 함수 추가
-  채팅방 조회 시 수신한 메시지 읽음 처리
 - jpql 작성 및 repository 테스트
 - 입찰 아이디로 조회, 채팅방 아이디로 조회에 repository 함수 호출

### 💫 작업 요약

- 채팅방 메시지 조회 API
- 채팅방 메시지 읽음 처리 채팅방 상세 조회 비즈니스 로직에 추가

### 🔍 중점적으로 리뷰 할 부분

- 채팅방 메시지 조회 시 유저 권한도 체크해야 하는지 아니면 채팅방 조회할 때만 호출(여기서 한번 권한 체크)하니까 상관없는지

2024-03-17 12:46 UTC, oridori2705 approved these changes

2024-03-17 12:46 UTC, merged

2024-03-17 13:59 UTC, ParkJuhan94 requested changes
고생하셨어요 리뷰 남겼습니다~

2024-03-17 13:59 UTC, ParkJuhan94 commented on api/src/test/java/dev/handsup/chat/controller/ChatRoomApiControllerTest.java
> +		mockMvc.perform(get("/api/auctions/chat-rooms/{chatRoomId}/messages", bidding.getId())
chatRoom1.getId() 아닐까요??

2024-03-17 13:59 UTC, ParkJuhan94 commented on api/src/test/java/dev/handsup/chat/controller/ChatRoomApiControllerTest.java
> +		ChatRoom chatRoom2 = ChatRoomFixture.chatRoom(seller, bidding);
chatRoom2 를 chatRoom1 과 똑같은 seller,bidding 으로 생성해주는건 비즈니스 로직에 안 맞지 않을까요??
해당 케이스에 대한 예외처리가 필요할 거 같아요~

2024-03-17 13:59 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/chat/dto/ChatMessageMapper.java
> +			chatMessage.getCreatedAt().toString()
메시지 조회면 senderId / senderNickname / senderProfileImage / createdAt / content 정도 필요하지 않을까요??

2024-03-17 13:59 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
>  public class ChatRoomService {
ChatRoomService 에서 Bidding 조회시,
즉시 로딩과 지연 로딩을 섞어 사용하는 것이 좋을 수 있을 것 같아요!

2024-03-17 13:59 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
> +	public PageResponse<ChatMessageResponse> getChatRoomMessages(Long chatRoomId,Pageable pageable) {
Long chatRoomId,Pageable pageable 코드 리포맷팅이 안 된 것 같아요~

2024-03-17 13:59 UTC, ParkJuhan94 commented on core/src/test/java/dev/handsup/chat/repository/ChatMessageRepositoryTest.java
> +		ProductCategory category = productCategoryRepository.save(ProductFixture.productCategory("디지털 기기"));
bookMarkApiControllerTest - setUp() 참고하시면  
productCategory 처리와 Auction 생성부분 유지보수가 좋아질 거 같아요~

2024-03-18 03:14 UTC, hyun2371 commented on core/src/main/java/dev/handsup/chat/dto/ChatMessageMapper.java
> +			chatMessage.getCreatedAt().toString()
수신자 닉네임이랑 프로필 이미지는 채팅방 상세 조회에서 보내주기 때문에 괜찮을 것 같습니다~

2024-03-18 04:01 UTC, hyun2371 commented on core/src/main/java/dev/handsup/chat/service/ChatRoomService.java
>  public class ChatRoomService {
bidding 조회하는 함수(채팅방 등록, 채팅방 아이디로 채팅방 조회, 입찰 아이디로 채팅방 조회) 모두 bidding.getBidder(), bidding.getAuction()으로 조회를 하고 있어서 fetch join을 사용하는게 좋은 것 같습니다!