[feat] : 인기 검색어 조회
Programmers-HandsUp/BE-handsup pull request #42
Opened 2024-02-25 13:20 UTC by hyun2371

### 📑 작업 상세 내용

- search 패키지 분리
  - 기존 경매 검색 api -> auction 패키지에서 추출
- keyword enum 추가
  - 추후 백엔드에서 최근 검색어 구현해도 괜찮을 것 같아서 추가했습니다.  
- api 테스트 위해 redis 의존성 api 모듈에 추가
- RedisSearchRepository 및 테스트 추가
- 서비스, 컨트롤러 로직 작성 후 테스트

### 💫 작업 요약

- 인기 검색어 구현 위해 redisSearchRepository 추가

### 🔍 중점적으로 리뷰 할 부분

- RedisSearchRepository
- RedisSearchRepositoryTest
- SearchApiControllerTest

2024-02-26 12:35 UTC, ParkJuhan94 requested changes
레디스를 깔끔하게 잘 적용하신 것 같아요!!
리뷰 남겼습니다

2024-02-26 12:35 UTC, ParkJuhan94 commented on api/src/main/java/dev/handsup/search/controller/SearchApiController.java
> +	public ResponseEntity<PageResponse<AuctionSimpleResponse>> searchAuctions(
지금 보니까 searchAuctions 보다는 
검색된 경매들을 받아오는 `getSearchedAuctions` 가 좋아보이네요~

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
> +	public static Auction toAuction(RegisterAuctionRequest request, ProductCategory productCategory, User user) {
근데 이거랑 다른 커밋들 코드스타일 관련된 문제일까요?? 
자주 보이네요ㅠ

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/auction/repository/search/RedisSearchRepository.java
> +	public int getKeywordCount(String keyword) {
private 으로 지정해주면 좋겠네요

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/search/service/SearchService.java
> +		redisSearchRepository.increaseSearchCount(condition.keyword());
레디스 DB에 카운트 변화가 일어나야하는데
여기서 @Transactional(readOnly = true) 를 사용해도 문제가 없을까요?

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/auction/repository/search/RedisSearchRepository.java
> +			.reverseRangeWithScores(key, 0, 9);
`9` : 10개의 인기검색어 라는 의미를 담도록 controller 메서드의 파라미터로 빼주는게 좋겠네요!

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/auction/repository/search/RedisSearchRepository.java
> +		Double score = redisTemplate.opsForZSet().score(KeywordType.POPULAR.getKey(), keyword);
score 가 정수일 것 같은데 꼭 Double 로 받아야하는걸까요?

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/search/dto/PopularKeywordResponse.java
> +public record PopularKeywordResponse(
@NoArgsConstructor(access = PRIVATE) 가 붙어야할것같네요~

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/test/java/dev/handsup/auction/repository/search/RedisSearchRepositoryTest.java
> +	public void clear() {
DatabaseCleaner 대신 해줘야하는 걸까요?

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/test/java/dev/handsup/auction/repository/search/RedisSearchRepositoryTest.java
> +	@DisplayName("[검색어를 인기순으로 조회할 수 있다.]")
카운트가 동일할 때에는 어떤 기준으로 정렬해서 조회해오나요 ?? 
동일할 때 정렬 기준에대한 테스트도 들어가야할 것 같아요

2024-02-26 12:35 UTC, ParkJuhan94 commented on core/src/test/java/dev/handsup/search/service/SearchServiceTest.java
> +	void getPopularKeywords() {
`여기서도 마찬가지로`

카운트가 동일할 때에는 어떤 기준으로 정렬해서 조회해오나요 ??
동일할 때 정렬 기준에대한 테스트도 들어가야할 것 같아요

2024-02-26 13:21 UTC, hyun2371 commented on core/src/main/java/dev/handsup/auction/repository/search/RedisSearchRepository.java
> +		Double score = redisTemplate.opsForZSet().score(KeywordType.POPULAR.getKey(), keyword);
redisTemplate 내장함수에서 Double로 반환됩니다!

2024-02-26 13:24 UTC, hyun2371 commented on core/src/test/java/dev/handsup/auction/repository/search/RedisSearchRepositoryTest.java
> +	public void clear() {
databaseCleaner는 말 그대로 DB 테이블만 비워줍니다! redis 데이터는 따로 지워줘야 해요~

2024-02-26 13:26 UTC, hyun2371 commented on core/src/main/java/dev/handsup/auction/repository/search/RedisSearchRepository.java
> +	public int getKeywordCount(String keyword) {
그러면 테스트 코드에서 오류가 발생합니다!

2024-02-26 13:28 UTC, hyun2371 commented on core/src/main/java/dev/handsup/auction/dto/mapper/AuctionMapper.java
> +	public static Auction toAuction(RegisterAuctionRequest request, ProductCategory productCategory, User user) {
<img width="652" alt="image" src="https://github.com/Programmers-HandsUp/BE-handsup/assets/77109954/8519162f-d062-4269-b135-a9338e5a5ebc">
동일한지 확인부탁드려요!

2024-02-26 13:33 UTC, hyun2371 commented on core/src/test/java/dev/handsup/auction/repository/search/RedisSearchRepositoryTest.java
> +	@DisplayName("[검색어를 인기순으로 조회할 수 있다.]")
항상 최근 검색된 순으로 정렬됩니다!

2024-02-27 04:20 UTC, hyun2371 commented on core/src/main/java/dev/handsup/search/dto/PopularKeywordResponse.java
> +public record PopularKeywordResponse(
`NoArgsConstructor is only supported on a class or an enum.`
record 필드들은 final이기 때문에 기본 생성자로 생성될 수 없습니다!

2024-02-27 04:22 UTC, hyun2371 commented on core/src/main/java/dev/handsup/auction/repository/search/RedisSearchRepository.java
> +			.reverseRangeWithScores(key, 0, 9);
count 변수 추가해서 service에서 넣어주도록 변경했습니다!

2024-02-27 04:26 UTC, hyun2371 commented on api/src/main/java/dev/handsup/search/controller/SearchApiController.java
> +	public ResponseEntity<PageResponse<AuctionSimpleResponse>> searchAuctions(
http 메서드가 post라서 헷갈릴 수 있기 때문에 searchAuctions도 괜찮은 것 같습니다!

2024-02-27 04:36 UTC, hyun2371 commented on core/src/main/java/dev/handsup/search/service/SearchService.java
> +		redisSearchRepository.increaseSearchCount(condition.keyword());
@Transactional을 관계형 데이터베이스 트랜잭션을 관리하는데 사용되어서 redis에 영향을 주지 않습니다!

2024-02-27 04:42 UTC, ParkJuhan94 approved these changes

2024-02-27 04:42 UTC, merged