[feat] : 경매 추천 API
Programmers-HandsUp/BE-handsup pull request #50
Opened 2024-03-01 09:19 UTC by hyun2371

close #49 
### 📑 작업 상세 내용
- 경매 추천 API 추가
  - 정렬 기준에 따라 조회 (입찰수, 마감일, 북마크수, 최근생성)
  - 지역에 따른 필터링
  - 정렬 기준은 필수고, 지역 필터링은 선택
- 검색 API 수정
  - 시, 구, 동 필터 오류 수정
  - 정렬 기준 좁힘(입찰수,마감일,북마크수,최근생성으로 정렬 가능하게)
 

### 💫 작업 요약

- 경매 추천 API 추가
- 검색 API 오류 및 정렬 기준 수정

### 🔍 중점적으로 리뷰 할 부분

- auctionRepositoryQueryImpl
- auctionRepositoryQueryImplTest

2024-03-01 20:36 UTC, ParkJuhan94 commented
고생하셨습니다 리뷰하겠습니다 !!

2024-03-01 20:41 UTC, ParkJuhan94 commented
```
@BeforeEach
	void setUp() {
		productCategory = ProductFixture.productCategory(DIGITAL_DEVICE);
		productCategoryRepository.save(productCategory);
		userRepository.save(user);
	}
```

Auction 을 생성하는 테스트마다
ProductCategory 를 저장해주는 것이 유지보수에도 안 좋고, 
테스트 속도에 영향을 주는 것 같아요.
테스트 시간이 점점 늘어가는게 느껴져서 고민이네요!

아래처럼 `DatabaseCleaner` 의 `initTableNames`() 를 수정하면
truncate() 에서 ProductCategory 테이블을 제외하고 지울 수 있을 것 같네요.


```
 @PostConstruct
    @SuppressWarnings("unchecked")
    private void initTableNames() {
        List<Object> tableInfoList = entityManager.createNativeQuery("SHOW TABLES").getResultList();
        tableInfoList.forEach(tableInfo -> {
            String tableName = String.valueOf(tableInfo);
            // productCategory 테이블을 제외하고 리스트에 추가
            if (!tableName.equalsIgnoreCase("productCategory")) {
                tableNames.add(tableName);
            }
        });
    }
```

2024-03-01 20:43 UTC, ParkJuhan94 commented
추가로 ApiTestSupport 에서

@PostConstruct 
sutUpUser() 처럼

@PostConstruct
setupProductCategory() 를 만들어주면 되겠네요!

그러면 Auction 을 생성해야하는 테스트들이 더 좋아질 것 같아요~!

2024-03-01 20:48 UTC, ParkJuhan94 commented
[“회원”님 이건 어떠세요?] 섹션(회원가입에서 관심 카테고리로 지정된 물품 중 관심 등록 순) 

메인페이지의 이 섹션은 보류인 걸까요?

2024-03-01 21:00 UTC, ParkJuhan94 requested changes

2024-03-01 21:00 UTC, ParkJuhan94 commented on api/src/main/java/dev/handsup/auction/controller/AuctionApiController.java
> +	@Operation(summary = "메인 페이지 추천 API", description = "정렬 조건에 따라 경매를 추천한다.")
메인 페이지 추천 API -> 경매를 추천한다는 말이 필요할 것 같아요

2024-03-01 21:00 UTC, ParkJuhan94 commented on api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
>  	@DisplayName("[경매를 상세정보를 조회할 수 있다.]")
를 이 빠져야겠네요!

2024-03-01 21:52 UTC, ParkJuhan94 requested changes

2024-03-01 21:52 UTC, ParkJuhan94 commented on api/src/test/java/dev/handsup/auction/controller/AuctionApiControllerTest.java
> +		Auction auction3 = AuctionFixture.auction(productCategory, "2024-03-08", si, gu, dong2);
auction1
auction2
auction3 
의 저 날짜들이 endDate 라는 것을 필드로 뽑아줘야 테스트의 의미를 알 수 있을 것 같아요!

2024-03-01 21:52 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
> +				case "마감일" -> auction.endDate.asc();
sort 이름을 한글로 수정한 것 좋네요!

2024-03-01 21:52 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
> +			.orElse(auction.createdAt.desc()); // 기본값 최신순
```
default -> auction.createdAt.desc();

.orElse(auction.createdAt.desc()); 
```

두 코드가 겹치지는 않나요??
둘 다 필요한걸까요?

2024-03-01 21:52 UTC, ParkJuhan94 commented on core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
> +		ReflectionTestUtils.setField(auction1, "biddingCount", 4);
테스트에서 필드를 지정해주고싶은 경우

- ReflectionTestUtils.setField()
- Fixture 에 필드를 넣어주는 생성자 추가

둘 중 선택하는 기준이 있으실까요??

2024-03-01 21:52 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepository.java
> +	Slice<Auction> sortAuctionByCriteria(String si, String gu, String dong, Pageable pageable);
String si, String gu, String dong
이 있는 경우와 없는 경우를 
메서드로 분리하는 것은 어떻게 생각하시나요?

테스트에서 
sortAuctionByCriteria(null, null, null, pageRequest) 
가 있는게 어색해보이네용

2024-03-01 21:52 UTC, ParkJuhan94 commented on core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
> +		assertThat(auctions).containsExactly(auction2, auction1);
good

2024-03-02 07:06 UTC, hyun2371 commented on core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImpl.java
> +			.orElse(auction.createdAt.desc()); // 기본값 최신순
- default
`switch expression`을 사용해서 바로 반환값을 받아오기 때문에 default가 없으면 오류가 납니다.
- orElse
 sort값이 없을 수도 있기 때문에 Optional로 반환되어 orElse가 필요합니다.

2024-03-02 07:16 UTC, hyun2371 commented on core/src/main/java/dev/handsup/auction/repository/auction/AuctionQueryRepository.java
> +	Slice<Auction> sortAuctionByCriteria(String si, String gu, String dong, Pageable pageable);
필터, 정렬 기능을 유연하게 가져가고자 querydsl을 쓴거라서요! 분리하지 않고 그대로 가져가는게 좋을 것 같습니다.

2024-03-02 07:44 UTC, hyun2371 commented
> [“회원”님 이건 어떠세요?] 섹션(회원가입에서 관심 카테고리로 지정된 물품 중 관심 등록 순)
> 
> 메인페이지의 이 섹션은 보류인 걸까요?
아직 회원 가입에서 관심 카테고리를 받고 저장하는 기능이 없어 구현하지 않았습니다. 해당 기능 구현되면 API 설계하겠습니다

2024-03-02 07:55 UTC, hyun2371 commented on core/src/test/java/dev/handsup/auction/repository/auction/AuctionQueryRepositoryImplTest.java
> +		ReflectionTestUtils.setField(auction1, "biddingCount", 4);
biddingCount, bookmarkCount 같이 기본값이 지정되어 있는 필드들은  setField로 넣고 있습니다~

2024-03-02 08:24 UTC, hyun2371 commented
> 추가로 `ApiTestSupport` 에서
> 
> ```
> @PostConstruct 
> sutUpUser()
> ```
> 
> 처럼
> 
> ```
> @PostConstruct
> setupProductCategory()
> ```
> 
> 를 만들어주면 되겠네요!
> 
> 그러면 `AuctionFixtrue, Auction 의 테스트용 생성자`마다 파라미터 `ProductCategory` 를 생략해줄 수 있겠네요

시도해봤는데 productCategory는 잘 truncate되지만 productCategory id가 null이라고 뜨네요. 일단 그대로 쓰고 기능 구현 다 한 다음에 리팩토링해도 될 것 같아요.

2024-03-02 13:28 UTC, ParkJuhan94 approved these changes

2024-03-03 01:58 UTC, merged