[feat] : websocket + stomp로 채팅 메시지 구현
Programmers-HandsUp/BE-handsup pull request #75
Opened 2024-03-08 09:15 UTC by hyun2371

### 📑 작업 상세 내용
- BiddingService 오류 수정
  - 지연 로딩 proxy 객체 initialize 에러
  - `@Transactional`추가
 - websocket 의존성 및 stomp 설정 추가
  -  websocket 테스트
- message 저장 로직 작성
### 💫 작업 요약
- 채팅 메시지 등록 로직 구현

### 🔍 중점적으로 리뷰 할 부분
- chatApiController

### 계획
현재는 spring 인메모리 브로커 사용
추후 redis 혹은 kafka로 메시지 브로커 구현 예정
message 저장 로직 mongoDB로 마이그레이션

2024-03-09 11:45 UTC, ParkJuhan94 commented
고생하셨습니다 리뷰하겠습니다~

2024-03-09 15:32 UTC, ParkJuhan94 approved these changes

2024-03-09 15:32 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/chat/service/ChatMessageService.java
> +	public ChatMessageResponse registerChatMessage(Long chatRoomId, ChatMessageRequest request) {
@Transactional 이 없어도 될까요 ?

2024-03-09 15:32 UTC, ParkJuhan94 commented on core/src/testFixtures/java/dev/handsup/fixture/ChatMessageFixture.java
> +		ReflectionTestUtils.setField(chatMessage, "createdAt", LocalDateTime.now());
LocalDateTime.now() 로 세팅하면  
ChatMessageFixture 를 코드에서 생성해줄 때의 시간으로 설정이 되는걸까요?

2024-03-09 15:34 UTC, ParkJuhan94 requested changes

2024-03-09 15:34 UTC, ParkJuhan94 commented on api/src/test/java/dev/handsup/chat/controller/WebSocketTest.java
> +	private final User seller = UserFixture.user(); // loginUser
loginUser 로 사용할 때는 ApiTestSupport 의 
user 필드를 레퍼런스로 받아도 되지 않을까요??

`private final User seller = user;`

2024-03-09 15:34 UTC, ParkJuhan94 approved these changes

2024-03-10 02:28 UTC, hyun2371 commented on core/src/testFixtures/java/dev/handsup/fixture/ChatMessageFixture.java
> +		ReflectionTestUtils.setField(chatMessage, "createdAt", LocalDateTime.now());
setField 호출하는 시점 시간으로 설정될 것 같습니다.
null 에러 없앨 목적으로 작성했습니다

2024-03-10 02:28 UTC, hyun2371 commented on api/src/test/java/dev/handsup/chat/controller/WebSocketTest.java
> +	private final User seller = UserFixture.user(); // loginUser
넵 그렇게 수정하겠습니다!

2024-03-10 06:48 UTC, hyun2371 commented on core/src/main/java/dev/handsup/chat/service/ChatMessageService.java
> +	public ChatMessageResponse registerChatMessage(Long chatRoomId, ChatMessageRequest request) {
추가했습니다!

2024-03-10 06:48 UTC, merged