거래 완료 및 거래 취소 API 구현
Programmers-HandsUp/BE-handsup pull request #77
Opened 2024-03-09 13:28 UTC by hyun2371

close #76 
### 📑 작업 상세 내용
- 거래 완료 API 구현
  - buyer 할당
- TradingStatus 추가
- bidding 내 상태 변경 메서드 추가 
- 기존 입찰 등록 로직에 첫번째 입찰일 경우 준비중으로 변경하는 로직 추가
### 💫 작업 요약
- 거래 완료 API 구현
- 거래 취소 API 구현

### 🔍 중점적으로 리뷰 할 부분
- Enum 클래스 TradingStatus 네이밍
- biddingService 상태 변경 로직

2024-03-11 09:43 UTC, ParkJuhan94 commented
고생하셨습니다~

2024-03-11 11:08 UTC, ParkJuhan94 requested changes

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/bidding/domain/Bidding.java
> +	private TradingStatus status;
문자열로 저장해야하지 않을까요?

```
@Enumerated(EnumType.STRING)
    @Column(name = "trading_status", nullable = false)
    private TradingStatus status;
```

로 매핑해줘도 좋겠네요

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/bidding/domain/Bidding.java
> +	public void completeTrading() {
비즈니스 메서드 네이밍을 직관적으로 변경하는건 어떨까요?
`setTradingStatusComplete()` 라든지?

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/bidding/domain/Bidding.java
> +	private TradingStatus status;
필드네임을 tradingStatus 그대로 가져가는건 어떨까요?

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/bidding/service/BiddingService.java
> +		if (isFirstBidding)
대괄호는 생략 안해주는게 좋은 것 같아요!

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/bidding/service/BiddingService.java
> +			savedBidding.prepareTrading(); // 첫 입찰일 경우 준비중 상태로 변경
준비중이라는게, 경매 타이머가 끝났을 때
입찰 순서는 왔는데 판매자가 채팅하기 전 상태인 걸로 이해를 했어요.

근데 첫 입찰일 경우 준비중 상태로 변경하면,

1. 준비중
2. 준비중 - 대기중
3. 대기중 - 준비중 - 대기중
4. 대기중 - 대기중 - 준비중 - 대기중

이런식으로 되는 상황이
의도한게 맞으실까요??

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/bidding/service/BiddingService.java
> +		biddingRepository.findFirstByStatus(TradingStatus.WAITING) // 다음 입찰 준비중 상태로 변경
현재 입찰을 취소하면 
다음 입찰은 진행중으로 바뀌어야하지 않을까요??

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/main/java/dev/handsup/bidding/service/BiddingService.java
> +		if (!Objects.equals(bidding.getAuction().getSeller().getId(), seller.getId())) {
Good

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/testFixtures/java/dev/handsup/fixture/BiddingFixture.java
> +	public static Bidding bidding(User user, Auction auction, TradingStatus status) {
id 지정 여부에 따라서 다르게 메서드 분리하려고
user 와 auction 파라미터 순서를 바꾸신것 같은데 좀 어색한 것 같아요.

2024-03-11 11:08 UTC, ParkJuhan94 commented on core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
> +		Bidding bidding2 = BiddingFixture.bidding(auction, bidder, TradingStatus.WAITING);
테스트에서도 
bidding2 는 bidding1 보다 `1000원 높아야한다는 비즈니스 룰`을 지키는게
좋을 거 같아요!

2024-03-12 11:54 UTC, hyun2371 commented on core/src/main/java/dev/handsup/bidding/domain/Bidding.java
> +	private TradingStatus status;
오 큰일날뻔했네요.. 수정하겠습니다.

2024-03-12 12:03 UTC, hyun2371 commented on core/src/testFixtures/java/dev/handsup/fixture/BiddingFixture.java
> +	public static Bidding bidding(User user, Auction auction, TradingStatus status) {
저는 메서드명을 바꾸는 것보다 파라미터 순서를 바꾸는게 오버로딩 되어서 더 나을 것 같다고 생각했는데 혹시 다른 방법이 있을까요?

2024-03-12 12:06 UTC, hyun2371 commented on core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
> +		Bidding bidding2 = BiddingFixture.bidding(auction, bidder, TradingStatus.WAITING);
픽스처 추가해서 비즈니스 요구사항 반영하였습니다!

2024-03-12 12:07 UTC, hyun2371 commented on core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
> +		Bidding bidding2 = BiddingFixture.bidding(auction, bidder, TradingStatus.WAITING);
주한님이 작성하신 입찰 목록 테스트에도 해당 요구사항이 반영되어야 할 것 같아요!

2024-03-12 12:12 UTC, hyun2371 commented on core/src/main/java/dev/handsup/bidding/service/BiddingService.java
> +		biddingRepository.findFirstByStatus(TradingStatus.WAITING) // 다음 입찰 준비중 상태로 변경
findFirstByStatus로 대기중인 입찰들 중 최상위 입찰을 진행중으로 변경합니다!

2024-03-12 13:42 UTC, hyun2371 commented
최종 적용 사항
- 입찰자는 중복 입찰 가능 (-> 매번 채팅방 생성 비효율적)
  - DB 상 채팅방의 기본키가 (`경매아이디`, `입찰자 아이디` )
- 채팅방에 `최근 입찰 아이디`를 저장
  - 채팅방에 거래 상태 표시& 거래 완료 로직 구현 위해 필요

- 채팅방 등록
  - i) 중복 입찰로 인해 판매자와 입찰자 간 채팅방 존재
    - 최근 입찰 아이디 요청된 입찰 아이디로 갱신 
    - 기존 채팅방 아이디 반환 
  - ii) 최초 입찰
    - 생성된 채팅방 아이디 반환

2024-03-12 13:43 UTC, hyun2371 commented
채팅방 등록 로직을 위 설명에 맞게 변경하였습니다.
또한 currentBiddingId를 추가 저장함에 따라 기존 채팅방 조회 로직 및 테스트 코드도 수정되었습니다!

2024-03-12 13:44 UTC, hyun2371 commented on core/src/main/java/dev/handsup/bidding/service/BiddingService.java
> +			savedBidding.prepareTrading(); // 첫 입찰일 경우 준비중 상태로 변경
준비중
준비중 - 대기중
취소 - 준비중 - 대기중
이런 식으로 변경됩니다

2024-03-12 13:45 UTC, hyun2371 commented on core/src/main/java/dev/handsup/bidding/service/BiddingService.java
> +			savedBidding.prepareTrading(); // 첫 입찰일 경우 준비중 상태로 변경
<img width="619" alt="image" src="https://github.com/Programmers-HandsUp/BE-handsup/assets/77109954/66a55036-19f8-4e93-95b1-339bd5d020b3">

2024-03-12 17:21 UTC, ParkJuhan94 commented on core/src/testFixtures/java/dev/handsup/fixture/BiddingFixture.java
> +	public static Bidding bidding(User user, Auction auction, TradingStatus status) {
오버로딩으로 사용하면
추후에 BiddingFixture.bidding() 을 사용할 때 한 번 더 들여다봐야할 것 같아요!

아니면 파라미터로 세팅할 id 를 넣어주는것도 괜찮겠네요!

2024-03-12 17:23 UTC, ParkJuhan94 commented on core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
> +		Bidding bidding2 = BiddingFixture.bidding(auction, bidder, TradingStatus.WAITING);
```
Bidding bidding1 = Bidding.of(40000, auction, user);
		Bidding bidding2 = Bidding.of(30000, auction, user);
		Bidding bidding3 = Bidding.of(20000, auction, user);
```

으로 입찰가 10000원씩 높게 되어있는데 바꿔야 하는걸까요?

2024-03-13 01:29 UTC, hyun2371 commented on core/src/test/java/dev/handsup/bidding/service/BiddingServiceTest.java
> +		Bidding bidding2 = BiddingFixture.bidding(auction, bidder, TradingStatus.WAITING);
가격이 낮은 순으로 저장되어야 하는거 아닌가 생각했는데 모킹해서 결과를 반환하니까 상관없을 것 같네요~

2024-03-13 06:47 UTC, merged